version: '3.8'

services:
  backend:
    container_name: backend-prod
    image: 2shul/nest-app-deploy-test:latest
    ports:
      - '3000:3000' # <- nestJS
    env_file:
      - .env.production
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        until nc -z db 3306;
        do echo '⏳ Waiting for MySQL...'; sleep 2; done &&
        echo '✅ MySQL ready. Starting app...' &&
        node dist/main
      "
  db:
    image: mysql:8.0
    container_name: mysql-prod
    command:
      [
        '--default-authentication-plugin=mysql_native_password',
        '--require_secure_transport=OFF',
        '--ssl=0',
        '--skip_ssl',
      ]
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env.production
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p${MYSQL_ROOT_PASSWORD}']
      interval: 5s
      timeout: 2s
      retries: 10
volumes:
  db-data:
