version: '3.8'

services:
  backend:
    container_name: backend-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000" # <- nestJS
      - "5555:5555" # <- prisma studio
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.development
    command: npm run start:dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-dev
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--require_secure_transport=OFF",
        "--ssl=0",
        "--skip_ssl"
      ]
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env.development

volumes:
  db-data: