version: '3.8'

services:
  backend:
    container_name: backend-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3000:3000" # <- nestJS
    env_file:
      - .env.production
    depends_on:
      - db
    networks:
      - backend
    command: ["node", "dist/main"]

  db:
    image: mysql:8.0
    container_name: mysql-prod
    networks:
      - backend
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--require_secure_transport=OFF",
        "--ssl=0",
        "--skip_ssl"
      ]
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env.production
volumes:
  db-data:
networks:
  backend: